# Generated by Django 5.0 on 2024-03-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
    ]
