# Generated by Django 5.0 on 2024-03-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sku_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
