# Generated by Django 5.0 on 2024-03-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_sku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
