# Generated by Django 5.0 on 2024-03-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_sku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
