# Generated by Django 5.0 on 2024-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='user_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
