# Generated by Django 5.0 on 2024-04-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_seller_id_inventory_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='user_id',
            new_name='seller',
        ),
    ]
