# Generated by Django 5.0 on 2024-04-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_user_id_inventory_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
