# Generated by Django 5.0 on 2024-03-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_transaction_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cart_item',
            table='cart_item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='order_item',
            table='order_item',
        ),
    ]
