# Generated by Django 5.0 on 2024-03-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_table_alter_cart_item_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='available', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='status',
            field=models.CharField(default='available', max_length=50, null=True),
        ),
    ]
