# Generated by Django 5.0 on 2024-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_status_cart_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='out_of_stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
