# Generated by Django 5.0 on 2024-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='seller_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
