# Generated by Django 5.0 on 2024-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart_item_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
