# Generated by Django 5.0 on 2024-03-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_seller_order_user_order_remove_order_item_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_order_item',
            old_name='Seller_order_id',
            new_name='seller_order_id',
        ),
        migrations.AddField(
            model_name='user_order',
            name='item_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_order_item',
            name='item_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
