# Generated by Django 5.0 on 2024-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_seller_order_id_seller_order_item_seller_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_order',
            name='item_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='seller_order_item',
            name='item_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
