# Generated by Django 5.0 on 2024-03-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_seller_order_item_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_order',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='seller_order_item',
            name='item_status',
        ),
    ]
