# Generated by Django 5.0 on 2024-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_seller_order_item_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_order',
            name='user_order_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
