# Generated by Django 5.0 on 2024-03-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_seller_order_user_id_alter_user_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_order',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
