# Generated by Django 5.0 on 2024-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_seller_order_user_id_alter_user_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seller_order_item',
            name='user_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
