# Generated by Django 5.0 on 2024-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cart_user_email_seller_order_item_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_order_item',
            name='user_email',
        ),
        migrations.AddField(
            model_name='seller_order',
            name='user_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
