# Generated by Django 5.0 on 2024-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_seller_order_item_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller_order_item',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_order_item',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
