# Generated by Django 5.0 on 2024-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_seller_order_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='seller_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
