# Generated by Django 5.0 on 2024-04-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_cart_item_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
