# Generated by Django 5.0 on 2024-04-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_cart_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
