# Generated by Django 5.0 on 2024-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_cart_status_alter_cart_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='seller_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
