# Generated by Django 5.0 on 2024-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('otp', models.IntegerField()),
            ],
            options={
                'db_table': 'user_otp',
            },
        ),
    ]
