# Generated by Django 5.0 on 2024-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='id',
        ),
        migrations.AlterField(
            model_name='userotp',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
