# Generated by Django 5.0 on 2024-04-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_remove_userotp_id_alter_userotp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
